name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          push: true
          tags: ralllfik/web-example

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-image-on-vm:
    name: Deploy web container on vm
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
    - name: Deploy to Azure WebVM0 via SSH
      uses: appleboy/ssh-action@master
      with:
        hosts: 20.114.222.125
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: docker run -p 80:80 ralllfik/web-example
    - name: Deploy to Azure WebVM1 via SSH
      uses: appleboy/ssh-action@master
      with:
        hosts: 20.119.242.73
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: docker run -p 80:80 ralllfik/web-example




