name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ralllfik/web-example
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-image-on-vm:
    name: Deploy web container on vm
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Azure WebVM0 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM0IP }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo docker stop web-example
          sudo docker rm web-example
          sudo docker pull ralllfik/web-example
          sudo docker run -d -p 80:80 --name web-example ralllfik/web-example
    - name: Deploy to Azure WebVM1 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM1IP }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo docker stop web-example
          sudo docker rm web-example
          sudo docker pull ralllfik/web-example
          sudo docker run -d -p 80:80 --name web-example ralllfik/web-example




